services:
  - type: web
    name: megler-monitor-web
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./MeglerMonitor/Dockerfile.web
    dockerContext: ./MeglerMonitor
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          type: web
          name: megler-monitor-api
          property: host
      - key: NODE_ENV
        value: "production"

  - type: web
    name: megler-monitor-api
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./infra/Dockerfile.api
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: megler-monitor-db
          property: connectionString
      - key: USE_SAMPLE
        value: "false"

databases:
  - name: megler-monitor-db
    databaseName: megler_monitor
    user: megler_user
    plan: free
    region: frankfurt
