services:
  - type: web
    name: megler-monitor-api
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: infra/Dockerfile.api
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: USE_SAMPLE
        value: "true"
      - key: RATE_LIMIT_MAX
        value: "500"

  - type: web
    name: megler-monitor-web
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: infra/Dockerfile.web
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          type: web
          name: megler-monitor-api
          property: host
      - key: API_BASE
        fromService:
          type: web
          name: megler-monitor-api
          property: host

databases:
  - name: megler-monitor-db
    databaseName: megler_monitor
    user: megler_user
    plan: free
    region: frankfurt
